### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Shiyinq** [muhibbudins/nuxt-project#1]
Sebelumnya Terimakasih atas tutorialnya, sangat membantu sekali :D 

Saya sudah ngikutin totorial agan sampe part 4 nih :D 
Namun ketika halaman detail localhost:3000/detail di akses secara langsung lewat url dan tanpa mengklik judul artikel, hasilnhya  muncul error gan :  

> Cannot read property 'name' of undefined

tapi kalo klik cardnya dulu sih gak muncul errornya.

Di tunggu kelanjutan artikel Nuxtnya  :D 
Terimakasih~
Shiyinq~

**Comment by muhibbudins** [comment]
Hi @Shiyinq ,

Terima kasih atas feedback yang di berikan, masalah di atas terjadi karena saya hanya menyimpan data artikel pada state vuex yang sebenarnya hanya sementara. Jadi ketika halaman detail di reload object dari artikel sebelumnya menghilang.

Tapi pada commit berikut [7ee4f11](https://github.com/muhibbudins/nuxt-project/commit/7ee4f11fab1d477e44317086b6410f001acd14d4), saya sudah menambahkan **vuex-persisted** untuk menangani masalah ini.

Jadi silahkan di `git pull` ulang.

Terima kasih 😄
